name: action_food
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_database: ^12.0.2 
  cloud_firestore: ^6.0.2
  http: ^1.5.0
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  cupertino_icons: ^1.0.8
  pix_flutter: ^2.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logoaction.png
    - assets/splashaction.png

# Splash Screen
flutter_native_splash:
  color: "#FFA500"
  image: "assets/splashaction.png"
  android_12:
    image: "assets/splashaction.png"
    android: true

# Launcher Icons
flutter_icons:
  android: true
  ios: false
  image_path: "assets/logoaction.png"
  app_name: "ActionFood"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logoaction.png"